name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm install -g @angular/cli@latest
    - run: ng build gorilla-ui  --configuration production
      working-directory: ./dist/gorilla-ui
    - run: npm version patch
    - run: npm pack
   
