name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm install -g @angular/cli@latest
    - run: ng build gorilla-ui
    - working-directory: ./dist/gorilla-ui
    - run: npm version patch
    - run: npm pack
    - name: Publish generated content to GitHub Pages
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
