name: workflow name

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:lib
      # - name: Test
      #   run: npm run test:ci
      - name: version
        working-directory: ./dist/gorilla-ui
        run: npm version patch
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist/gorilla-ui
      # - name: Archive code coverage result
      #   if: success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: deploy_coverage
      #     path: coverage
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
          path: ~/gorilla-ui
      - name: Display structure of downloaded files
        run: ls -R
      - name: Deploy to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          check-version: false
          access: public
          token: ${{ secrets.NPM_TOKEN }}

